# 버전은 현재, 0.2가 권장사항입니다.
version: 0.2

# 빌드 단계별로 원하는 명령을 입력합니다.
phases:
  # 빌드 전에 필요한 환경을 설치합니다.
  install:
    runtime-versions:
      nodejs: 18
  # 빌드 전에 수행할 명령을 입력합니다.
  pre_build:
    commands:
      - echo Buile Phase >> pre_build phase...
  # 빌드를 수행할 명령을 입력합니다.
  build:
    commands:
      - echo Buile Phase >> Build started on `date`
      - npm install
      - npm run build
  # 빌드 후에 수행할 명령을 입력합니다.
  post_build:
    commands:
      - echo Buile Phase >> Build completed on `date`
      - aws s3 sync ./dist/spa $S3_BUCKET --delete
# # 빌드 결과물로 나온 아티팩트에 대한 정보를 제공합니다.
# # 아티팩트는 s3루트에 codebuild 프로젝트 이름으로 폴더가 생성되고 하위에 결과가 업로드됨
# artifacts:
#   # 빌드 환경에서 빌드 출력 결과물이 생성되는 위치를 나타냅니다.
#   # '**/*'는 모든 파일을 재귀적으로 나타냅니다.
#   files:
#     - '**/*'
#   # 출력 base 폴더
#   base-directory: 'dist/spa'

